### ISSUE TITLE
Add uuidFilter for id's that are based on Symfony\Component\Uid V6

### ISSUE THREAD

**Issue by Jurgo** [webstacknl/api-platform-extensions-bundle#8]
In de app worden uuid v6 id's gebruikt terwijl het filter v1 ondersteund.

![image](https://user-images.githubusercontent.com/1120293/218409382-850ed03a-7217-408b-8778-fe6959cf8ed8.png)

PR's die hierop wachten: 
- https://github.com/webstacknl/rsa-frontend/pull/48

**Comment by mwansinck** [comment]
Kan dit niet native met Symfony + API platform?

**Comment by Jurgo** [comment]
@mwansinck ik heb tot op heden nog niets kunnen vinden over een uuid filter in API platform. Op de webs kwam ik een oplossing tegen met de SearchFilter maar dat lijkt niet te werken.

**Comment by Jurgo** [comment]
Is opgelost met versie 2.2.1 en 3.1.0
